name: 口令生成与部署

on:
  # 定时触发，每天UTC 0点运行
  schedule:
    - cron: '0 0 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出phone分支
        uses: actions/checkout@v4
        with:
          ref: phone
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: 生成随机口令
        id: generate_password
        run: |
          # 生成一个20位的随机字符串作为口令
          PASSWORD=$(openssl rand -hex 10)
          echo "password=$PASSWORD" >> $GITHUB_ENV
          echo "生成的口令: $PASSWORD"
      
      - name: 创建目录结构（如果不存在）
        run: |
          mkdir -p index
      
      - name: 更新或创建password.js文件
        run: |
          # 创建或更新password.js文件
          echo "const PASSWORD = '${{ env.password }}';" > password.js
          cat index/password.js
      
      - name: 提交更改
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add index/password.js
          git commit -m "自动更新口令 - $(date +'%Y-%m-%d %H:%M:%S')" || echo "没有更改需要提交"
          git push origin phone || echo "推送失败，可能没有更改"
      
      - name: 通知到个人微信
        run: |
          # 预留调用第三方服务通知个人微信的代码位置
          # 可使用企业微信机器人、Server酱等服务
          # 示例代码（需替换为实际的API调用）：
          # curl -X POST -H "Content-Type: application/json" \
          #   -d '{"text": "GitHub Pages口令已更新为: $PASSWORD"}' \
          #   https://api.example.com/wechat-notify
          echo "此处可添加通知个人微信的代码"
    
